"use client"

import { useState, useEffect } from "react"
import { toPng } from "html-to-image"
import jsPDF from "jspdf"
import { Footer } from "@/components/footer"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Loader2, Sparkles, Copy, Check, Lock, Briefcase, Building2 } from "lucide-react"
import { useAuth } from "@/lib/auth-context"
import { toast } from "sonner"
import { UserProfile } from "@/lib/cv-logic-engine"
import { CoverLetterTone } from "@/lib/cover-letter-logic"

export function CoverLetterGenerator() {
    const { profile, user } = useAuth()
    const [job, setJob] = useState({
        title: "",
        company: "",
        description: "",
        companyAddress: "",
        userAddress: ""
    })
    const [generatedLetter, setGeneratedLetter] = useState("")
    const [detectedTone, setDetectedTone] = useState<CoverLetterTone | null>(null)
    const [isLoading, setIsLoading] = useState(false)
    const [isCopied, setIsCopied] = useState(false)

    const isLocked = !job.title || !job.company

    const handleGenerate = async () => {
        if (isLocked) return

        setIsLoading(true)
        setGeneratedLetter("")

        // Construct minimal profile for API
        const userProfile: UserProfile = {
            status: profile?.status || 'employed',
            yearsExperience: 2, // Default fallback
            targetRole: job.title,
            skills: profile?.hardSkills || [],
            projectCount: 0,
            fullName: profile?.fullName,
            impact_metrics: profile?.impact_metrics || profile?.resumeData?.impactMetric,
            leadership_experience: profile?.leadership_experience || profile?.resumeData?.leadershipAction || profile?.resumeData?.leadership,
            unique_hook: profile?.unique_hook || profile?.resumeData?.professionalHook
        }

        try {
            const response = await fetch('/api/cover-letter', {
                method: 'POST',
                body: JSON.stringify({ profile: userProfile, job }),
            })

            if (!response.ok) throw new Error('Generation failed')

            const data = await response.json()
            setGeneratedLetter(data.text)
            setDetectedTone(data.tone)
            toast.success("Letters forged. Adaptation complete.")
        } catch (error) {
            toast.error("Process failed. Try again.")
        } finally {
            setIsLoading(false)
        }
    }

    const handleCopy = () => {
        navigator.clipboard.writeText(generatedLetter)
        setIsCopied(true)
        toast.info("Copied to clipboard. Now send it and forget it.")
        setTimeout(() => setIsCopied(false), 2000)
    }

    const handleDownloadPDF = async () => {
        if (!generatedLetter) return

        toast.info("Forging PDF document...")
        try {
            const doc = new jsPDF()

            // Header
            doc.setFont("helvetica", "bold")
            doc.setFontSize(22)
            doc.setTextColor(15, 23, 42) // Slate 900
            doc.text(profile?.fullName || "Candidate", 20, 30)

            doc.setFontSize(10)
            doc.setTextColor(100, 116, 139) // Slate 500
            doc.text(`${user?.email || ""} | ${profile?.location || "Freetown, Sierra Leone"}`, 20, 38)

            doc.setDrawColor(226, 232, 240) // Slate 200
            doc.line(20, 45, 190, 45)

            // Date
            doc.setFont("helvetica", "normal")
            doc.setFontSize(10)
            doc.setTextColor(100, 116, 139)
            doc.text(new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }), 20, 55)

            // Body
            doc.setFont("helvetica", "normal")
            doc.setFontSize(11)
            doc.setTextColor(51, 65, 85) // Slate 700

            const splitText = doc.splitTextToSize(generatedLetter, 170)
            doc.text(splitText, 20, 70)

            // Footer
            const pageCount = (doc as any).internal.getNumberOfPages()
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i)
                doc.setFontSize(8)
                doc.setTextColor(148, 163, 184)
                doc.text("Generated by CareerPilot Salone - AI Career OS", 105, 285, { align: "center" })
            }

            doc.save(`Cover_Letter_${job.company.replace(/\s+/g, '_')}.pdf`)
            toast.success("Tactical PDF exported.")
        } catch (error) {
            toast.error("PDF Forge failed.")
        }
    }

    return (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">

            {/* INPUT MODULE */}
            <Card className="p-8 border-none rounded-[2rem] bg-white shadow-xl shadow-indigo-500/5 space-y-6">
                <div className="space-y-2">
                    <h2 className="text-xl font-black uppercase tracking-tight text-slate-900 flex items-center gap-2">
                        <Briefcase className="w-5 h-5 text-indigo-600" />
                        Target Vector
                    </h2>
                    <p className="text-sm text-slate-500 font-medium">
                        Where are we aiming? Precision is key.
                    </p>
                </div>

                <div className="space-y-4">
                    <div className="space-y-2">
                        <Label className="uppercase text-xs font-bold text-slate-400 ml-1">Job Title <span className="text-red-400">*</span></Label>
                        <div className="relative">
                            <Briefcase className="absolute left-4 top-3.5 w-4 h-4 text-slate-300" />
                            <Input
                                placeholder="e.g. Senior Frontend Engineer"
                                className="pl-10 h-12 rounded-xl bg-slate-50 border-slate-200 focus-visible:ring-indigo-500"
                                value={job.title}
                                onChange={(e) => setJob({ ...job, title: e.target.value })}
                            />
                        </div>
                    </div>

                    <div className="space-y-2">
                        <Label className="uppercase text-xs font-bold text-slate-400 ml-1">Company Name <span className="text-red-400">*</span></Label>
                        <div className="relative">
                            <Building2 className="absolute left-4 top-3.5 w-4 h-4 text-slate-300" />
                            <Input
                                placeholder="e.g. Orange Sierra Leone"
                                className="pl-10 h-12 rounded-xl bg-slate-50 border-slate-200 focus-visible:ring-indigo-500"
                                value={job.company}
                                onChange={(e) => setJob({ ...job, company: e.target.value })}
                            />
                        </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="space-y-2">
                            <Label className="uppercase text-xs font-bold text-slate-400 ml-1">Your Address</Label>
                            <Input
                                placeholder="Your Return Address"
                                className="h-12 rounded-xl bg-slate-50 border-slate-200 focus-visible:ring-indigo-500"
                                value={job.userAddress}
                                onChange={(e) => setJob({ ...job, userAddress: e.target.value })}
                            />
                        </div>
                        <div className="space-y-2">
                            <Label className="uppercase text-xs font-bold text-slate-400 ml-1">Company Address</Label>
                            <Input
                                placeholder="Company Location"
                                className="h-12 rounded-xl bg-slate-50 border-slate-200 focus-visible:ring-indigo-500"
                                value={job.companyAddress}
                                onChange={(e) => setJob({ ...job, companyAddress: e.target.value })}
                            />
                        </div>
                    </div>

                    <div className="space-y-2">
                        <Label className="uppercase text-xs font-bold text-slate-400 ml-1">Job Description Snippet (Optional)</Label>
                        <Textarea
                            placeholder="Paste the key requirements here..."
                            className="rounded-xl bg-slate-50 border-slate-200 focus-visible:ring-indigo-500 resize-none"
                            rows={4}
                            value={job.description}
                            onChange={(e) => setJob({ ...job, description: e.target.value })}
                        />
                    </div>
                </div>

                <Button
                    className={`w-full h-14 rounded-xl font-bold uppercase tracking-wide text-xs transition-all ${isLocked ? 'bg-slate-100 text-slate-400 cursor-not-allowed' : 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-lg shadow-indigo-500/30'}`}
                    disabled={isLocked || isLoading}
                    onClick={handleGenerate}
                >
                    {isLoading ? (
                        <>
                            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                            Synthesizing...
                        </>
                    ) : isLocked ? (
                        <>
                            <Lock className="w-4 h-4 mr-2" />
                            Input Target to Unlock
                        </>
                    ) : (
                        <>
                            <Sparkles className="w-4 h-4 mr-2" />
                            Generate Disposable Letter
                        </>
                    )}
                </Button>
            </Card>


            {/* OUTPUT MODULE */}
            <div className={`transition-all duration-500 ${generatedLetter ? 'opacity-100 translate-y-0' : 'opacity-50 translate-y-4 grayscale blur-[1px]'}`}>
                <Card className="p-8 border-none rounded-[2rem] bg-white shadow-xl shadow-emerald-500/5 space-y-6 relative border-t-4 border-emerald-400">
                    <div className="flex items-center justify-between">
                        <div className="space-y-1">
                            <h3 className="text-sm font-black uppercase tracking-widest text-emerald-800">Generated Asset</h3>
                            {detectedTone && (
                                <Badge variant="outline" className="bg-emerald-50 text-emerald-600 border-emerald-200 uppercase text-[10px] tracking-wider">
                                    Detected Tone: {detectedTone}
                                </Badge>
                            )}
                        </div>
                        <div className="flex gap-2">
                            <Button
                                size="sm"
                                variant="outline"
                                onClick={handleDownloadPDF}
                                disabled={!generatedLetter}
                                className="h-9 px-4 rounded-xl border-emerald-100 bg-emerald-50/50 text-emerald-600 font-bold uppercase tracking-wide text-[10px] gap-2 hover:bg-emerald-100"
                            >
                                <Sparkles className="w-3.5 h-3.5" />
                                Download PDF
                            </Button>
                            <Button
                                size="icon"
                                variant="ghost"
                                onClick={handleCopy}
                                disabled={!generatedLetter}
                                className={isCopied ? "text-emerald-500 bg-emerald-50" : "text-slate-400 hover:text-slate-600"}
                            >
                                {isCopied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                            </Button>
                        </div>
                    </div>

                    <Textarea
                        className="min-h-[600px] border-none focus-visible:ring-0 p-0 text-slate-600 leading-relaxed font-medium resize-none bg-transparent"
                        value={generatedLetter || "Waiting for target data..."}
                        readOnly={false}
                        onChange={(e) => setGeneratedLetter(e.target.value)}
                    />

                    <div className="pt-6 border-t border-slate-100 flex justify-between items-center">
                        <p className="text-xs text-slate-400 italic">
                            *This letter is ephemeral. Copy it, send it, then discard it.
                        </p>
                    </div>
                </Card>
            </div>

        </div>
    )
}
