// Sierra Leone Career Knowledge Base
// Comprehensive data for local AI fallback system

export interface CareerInfo {
    id: string;
    title: string;
    industry: string;
    description: string;
    salaryRange: string;
    salaryUSD: string;
    demand: 'High' | 'Medium' | 'Low';
    requiredEducation: string[];
    requiredSkills: string[];
    localInstitutions: string[];
    growthPotential: string;
    keywords: string[];
    image: string;
    // Rule 1: Data Integrity
    roadmapId?: string;
    universityIds?: string[];
    mentorIds?: string[];
    source?: 'verified' | 'external/unverified';
}

export interface RoadmapTask {
    id: string;
    title: string;
    description: string;
    duration: string;
    completed: boolean;
    week: number;
}

export const SIERRA_LEONE_CAREERS: CareerInfo[] = [
    // --- CORE CAREERS (Original 12) ---
    {
        id: "software-developer",
        title: "Software Developer",
        industry: "Technology",
        description: "Design, develop, and maintain software applications and systems",
        salaryRange: "SLE 3,500 - 9,000 (approx. $150 - $400)/month",
        salaryUSD: "SLE 3,500 - 9,000 (approx. $150 - $400)/month",
        demand: "High",
        requiredEducation: ["Computer Science degree", "Self-taught with portfolio", "Coding bootcamp"],
        requiredSkills: ["JavaScript", "Python", "Problem-solving", "Git", "Web development"],
        localInstitutions: ["Fourah Bay College", "IPAM", "Njala University", "Online platforms (freeCodeCamp, Codecademy)"],
        growthPotential: "Excellent - Tech sector growing rapidly in Freetown",
        keywords: ["coding", "programming", "tech", "software", "developer", "web", "app"],
        image: "/images/sections/careers/software-developer.png",
        roadmapId: "software-developer",
        universityIds: ["fbc", "ipam", "bluecrest"],
        mentorIds: ["sengeh", "salima"],
        source: "verified"
    },
    {
        id: "nurse-healthcare-worker",
        title: "Nurse/Healthcare Worker",
        industry: "Healthcare",
        description: "Provide patient care, administer medications, and support medical teams",
        salaryRange: "SLE 2,800 - 6,800 (approx. $125 - $300)/month",
        salaryUSD: "SLE 2,800 - 6,800 (approx. $125 - $300)/month",
        demand: "High",
        requiredEducation: ["Nursing diploma/degree", "Medical training certificate"],
        requiredSkills: ["Patient care", "Medical knowledge", "Communication", "Empathy", "Emergency response"],
        localInstitutions: ["College of Medicine and Allied Health Sciences", "Njala University", "Holy Spirit Hospital School of Nursing"],
        growthPotential: "Very high - Healthcare infrastructure expanding",
        keywords: ["nurse", "healthcare", "medical", "doctor", "health", "patient", "hospital"],
        image: "/images/sections/careers/nurse-healthcare-worker.png",
        roadmapId: "nurse",
        universityIds: ["comahs", "njala"],
        mentorIds: ["demby"],
        source: "verified"
    },
    {
        id: "agricultural-officer",
        title: "Agricultural Officer",
        industry: "Agriculture",
        description: "Manage farming operations, improve crop yields, and advise farmers",
        salaryRange: "SLE 2,250 - 5,600 (approx. $100 - $250)/month",
        salaryUSD: "SLE 2,250 - 5,600 (approx. $100 - $250)/month",
        demand: "High",
        requiredEducation: ["Agriculture degree", "Agronomy certificate"],
        requiredSkills: ["Crop management", "Soil science", "Pest control", "Farm planning", "Extension services"],
        localInstitutions: ["Njala University", "Sierra Leone Agricultural Research Institute"],
        growthPotential: "Excellent - Agriculture is 60% of economy",
        keywords: ["farming", "agriculture", "crops", "agric", "farmer", "food", "cultivation"],
        image: "/images/sections/careers/agricultural-officer.png",
        roadmapId: "agripreneur",
        universityIds: ["njala", "etu"],
        mentorIds: ["kpaka"],
        source: "verified"
    },
    {
        id: "teacher-educator",
        title: "Teacher/Educator",
        industry: "Education",
        description: "Educate students, develop curriculum, and foster learning environments",
        salaryRange: "SLE 2,000 - 5,100 (approx. $90 - $225)/month",
        salaryUSD: "SLE 2,000 - 5,100 (approx. $90 - $225)/month",
        demand: "High",
        requiredEducation: ["Teaching certificate", "Education degree", "Subject specialization"],
        requiredSkills: ["Communication", "Patience", "Curriculum development", "Classroom management"],
        localInstitutions: ["Fourah Bay College", "Milton Margai College of Education", "Eastern Polytechnic"],
        growthPotential: "Good - Free Quality Education initiative expanding",
        keywords: ["teacher", "education", "teaching", "school", "classroom", "tutor", "lecturer"],
        image: "/images/sections/careers/teacher-educator.png",
        roadmapId: "teacher",
        universityIds: ["fbc", "mmtu", "ebkust"],
        mentorIds: ["alpha-bah"],
        source: "verified"
    },
    {
        id: "mining-engineer",
        title: "Mining Engineer",
        industry: "Mining",
        description: "Plan and oversee mining operations, ensure safety and efficiency",
        salaryRange: "SLE 5,600 - 13,500 (approx. $250 - $600)/month",
        salaryUSD: "SLE 5,600 - 13,500 (approx. $250 - $600)/month",
        demand: "High",
        requiredEducation: ["Mining engineering degree", "Geology degree"],
        requiredSkills: ["Geological analysis", "Safety protocols", "Equipment operation", "Project management"],
        localInstitutions: ["Fourah Bay College", "Njala University", "International training programs"],
        growthPotential: "Excellent - Mining is major economic sector",
        keywords: ["mining", "engineer", "geology", "minerals", "extraction", "diamonds", "gold"],
        image: "/images/sections/careers/mining-engineer.png",
        roadmapId: "mining-engineer",
        universityIds: ["fbc"],
        mentorIds: ["mattai"],
        source: "verified"
    },
    {
        id: "accountant",
        title: "Accountant",
        industry: "Finance",
        description: "Manage financial records, prepare reports, and ensure compliance",
        salaryRange: "SLE 3,400 - 7,900 (approx. $150 - $350)/month",
        salaryUSD: "SLE 3,400 - 7,900 (approx. $150 - $350)/month",
        demand: "Medium",
        requiredEducation: ["Accounting degree", "ACCA/CPA certification"],
        requiredSkills: ["Financial analysis", "Bookkeeping", "Tax preparation", "Excel", "Attention to detail"],
        localInstitutions: ["IPAM", "Fourah Bay College", "University of Makeni"],
        growthPotential: "Good - Every business needs accountants",
        keywords: ["accounting", "finance", "bookkeeping", "financial", "accountant", "money", "budget"],
        image: "/images/sections/careers/accountant.jpg",
        roadmapId: "accountant",
        universityIds: ["ipam", "fbc", "unimak"],
        mentorIds: ["bangura", "yakama"],
        source: "verified"
    },
    {
        id: "civil-engineer",
        title: "Civil Engineer",
        industry: "Engineering",
        description: "Design and supervise construction of infrastructure projects",
        salaryRange: "SLE 4,500 - 11,250 (approx. $200 - $500)/month",
        salaryUSD: "SLE 4,500 - 11,250 (approx. $200 - $500)/month",
        demand: "High",
        requiredEducation: ["Civil engineering degree"],
        requiredSkills: ["AutoCAD", "Structural design", "Project management", "Construction knowledge"],
        localInstitutions: ["Fourah Bay College", "Njala University", "COMAHS"],
        growthPotential: "Excellent - Infrastructure development ongoing",
        keywords: ["civil", "engineer", "construction", "building", "infrastructure", "roads", "bridges"],
        image: "/images/sections/careers/civil-engineer.png",
        roadmapId: "civil-engineer",
        universityIds: ["fbc", "etu"],
        mentorIds: ["mattai"],
        source: "verified"
    },
    {
        id: "marketing-manager",
        title: "Marketing Manager",
        industry: "Business",
        description: "Develop marketing strategies, manage campaigns, and drive sales",
        salaryRange: "SLE 3,900 - 9,000 (approx. $175 - $400)/month",
        salaryUSD: "SLE 3,900 - 9,000 (approx. $175 - $400)/month",
        demand: "Medium",
        requiredEducation: ["Marketing degree", "Business administration"],
        requiredSkills: ["Digital marketing", "Social media", "Brand management", "Communication", "Analytics"],
        localInstitutions: ["IPAM", "Fourah Bay College", "University of Makeni"],
        growthPotential: "Good - Growing business sector",
        keywords: ["marketing", "business", "sales", "advertising", "promotion", "brand", "digital"],
        image: "/images/sections/careers/account-manager.png",
        roadmapId: "marketing-manager",
        universityIds: ["ipam", "fbc", "unimak"],
        mentorIds: ["remoe", "akisawyerr"],
        source: "verified"
    },
    {
        id: "telecommunications-technician",
        title: "Telecommunications Technician",
        industry: "Technology",
        description: "Install, maintain, and repair telecommunications equipment",
        salaryRange: "SLE 2,800 - 6,750 (approx. $125 - $300)/month",
        salaryUSD: "SLE 2,800 - 6,750 (approx. $125 - $300)/month",
        demand: "High",
        requiredEducation: ["Technical diploma", "Electronics certificate"],
        requiredSkills: ["Network installation", "Troubleshooting", "Electronics", "Customer service"],
        localInstitutions: ["Eastern Polytechnic", "Technical institutes", "On-the-job training"],
        growthPotential: "Very high - Mobile/internet expansion",
        keywords: ["telecom", "telecommunications", "network", "phone", "internet", "technician", "mobile"],
        image: "/images/sections/careers/software-developer.png",
        roadmapId: "network-administrator",
        universityIds: ["bluecrest", "mmtu", "orange-digital"],
        mentorIds: ["salima"],
        source: "verified"
    },
    {
        id: "ngo-program-officer",
        title: "NGO Program Officer",
        industry: "Non-Profit",
        description: "Manage development programs, coordinate projects, and support communities",
        salaryRange: "SLE 3,400 - 8,400 (approx. $150 - $375)/month",
        salaryUSD: "SLE 3,400 - 8,400 (approx. $150 - $375)/month",
        demand: "Medium",
        requiredEducation: ["Development studies", "Social sciences degree", "Public health"],
        requiredSkills: ["Project management", "Community engagement", "Report writing", "Grant writing"],
        localInstitutions: ["Fourah Bay College", "Njala University", "IPAM"],
        growthPotential: "Good - Active NGO sector",
        keywords: ["ngo", "development", "nonprofit", "community", "social", "humanitarian", "aid"],
        image: "/images/sections/careers/account-manager.png",
        roadmapId: "project-manager",
        universityIds: ["fbc", "ipam", "unimak"],
        mentorIds: ["kaifala"],
        source: "verified"
    },
    {
        id: "electrician",
        title: "Electrician",
        industry: "Skilled Trade",
        description: "Install and maintain electrical systems in buildings and facilities",
        salaryRange: "SLE 2,250 - 6,200 (approx. $100 - $275)/month",
        salaryUSD: "SLE 2,250 - 6,200 (approx. $100 - $275)/month",
        demand: "High",
        requiredEducation: ["Technical training", "Apprenticeship", "Electrical certificate"],
        requiredSkills: ["Wiring", "Safety protocols", "Troubleshooting", "Blueprint reading"],
        localInstitutions: ["Eastern Polytechnic", "Technical institutes", "Trade schools"],
        growthPotential: "Very good - Construction boom in Freetown",
        keywords: ["electrician", "electrical", "wiring", "power", "electricity", "trade", "technician"],
        image: "/images/sections/careers/auto-mechanic.png",
        universityIds: ["mmtu", "etu", "gti"],
        mentorIds: [], // No verified mentor yet
        source: "external/unverified"
    },
    {
        id: "journalist",
        title: "Journalist",
        industry: "Media",
        description: "Report news, create content, and inform the public",
        salaryRange: "SLE 2,250 - 5,600 (approx. $100 - $250)/month",
        salaryUSD: "SLE 2,250 - 5,600 (approx. $100 - $250)/month",
        demand: "Medium",
        requiredEducation: ["Journalism degree", "Mass communication"],
        requiredSkills: ["Writing", "Research", "Interviewing", "Video editing", "Social media"],
        localInstitutions: ["Fourah Bay College", "IPAM", "Media training centers"],
        growthPotential: "Good - Growing media landscape",
        keywords: ["journalist", "media", "news", "reporter", "writing", "broadcasting", "communication"],
        image: "/images/sections/careers/account-manager.png",
        universityIds: ["fbc", "ipam"],
        mentorIds: ["remoe"],
        source: "verified"
    },

    // --- EXPANDED CAREERS (New & Detailed) ---
    {
        id: "network-administrator",
        title: "Network Administrator",
        industry: "Technology",
        description: "Maintain and secure organizational computer networks and data communication systems",
        salaryRange: "SLE 3,500 - 8,500 (approx. $155 - $380)/month",
        salaryUSD: "SLE 3,500 - 8,500 (approx. $155 - $380)/month",
        demand: "High",
        requiredEducation: ["Computer Science degree", "IT certifications (CCNA, Network+)", "Technical diploma"],
        requiredSkills: ["Network security", "Troubleshooting", "Server management", "Cisco systems", "Infrastructure design"],
        localInstitutions: ["Fourah Bay College", "BlueCrest College", "IPAM", "Technical institutes"],
        growthPotential: "Strong - Digital infrastructure expanding continuously",
        keywords: ["network", "admin", "it", "infrastructure", "systems", "security", "server"],
        image: "/images/sections/careers/software-developer.png",
        universityIds: ["fbc", "bluecrest"]
    },
    {
        id: "cybersecurity-analyst",
        title: "Cybersecurity Analyst",
        industry: "Technology",
        description: "Protect organizational networks and data from cyber threats and security breaches",
        salaryRange: "SLE 4,500 - 12,000 (approx. $200 - $530)/month",
        salaryUSD: "SLE 4,500 - 12,000 (approx. $200 - $530)/month",
        demand: "High",
        requiredEducation: ["Computer Science degree", "Cybersecurity certifications (CEH, CISSP)", "IT degree"],
        requiredSkills: ["Information security", "Threat analysis", "Encryption", "Security auditing", "Risk management"],
        localInstitutions: ["Fourah Bay College", "BlueCrest College", "Online certification programs"],
        growthPotential: "Excellent - Rapidly growing need in banking and government",
        keywords: ["cyber", "security", "hacker", "protection", "attacks", "information", "it"],
        image: "/images/sections/careers/software-developer.png",
        universityIds: ["fbc", "bluecrest"]
    },
    {
        id: "ux-ui-designer",
        title: "UX/UI Designer",
        industry: "Technology",
        description: "Design user-friendly interfaces and enhance user experience for digital products",
        salaryRange: "SLE 3,000 - 7,500 (approx. $135 - $330)/month",
        salaryUSD: "SLE 3,000 - 7,500 (approx. $135 - $330)/month",
        demand: "Medium",
        requiredEducation: ["Graphic design background", "IT degree", "Portfolio of design work"],
        requiredSkills: ["Figma", "User research", "Prototyping", "Visual design", "Wireframing"],
        localInstitutions: ["Limkokwing University", "BlueCrest College", "Online design schools"],
        growthPotential: "Emerging - Increasing focus on digital apps and services in SL",
        keywords: ["ui", "ux", "design", "interface", "experience", "user", "app", "web"],
        image: "/images/sections/careers/software-developer.png",
        universityIds: ["limkokwing", "bluecrest"]
    },
    {
        id: "graphic-designer",
        title: "Graphic Designer",
        industry: "Media",
        description: "Create visual concepts to communicate ideas that inspire, inform, and captivate consumers",
        salaryRange: "SLE 2,500 - 6,500 (approx. $110 - $290)/month",
        salaryUSD: "SLE 2,500 - 6,500 (approx. $110 - $290)/month",
        demand: "Medium",
        requiredEducation: ["Visual arts degree", "Mass communication", "Portfolio-based entry"],
        requiredSkills: ["Photoshop", "Illustrator", "Canva", "Typography", "Creative thinking"],
        localInstitutions: ["Limkokwing University", "Milton Margai University", "Independent studios"],
        growthPotential: "Stable - Every business and campaign needs branding",
        keywords: ["graphic", "design", "art", "creative", "branding", "logo", "visual"],
        image: "/images/sections/careers/account-manager.png",
        universityIds: ["limkokwing", "mmtu"]
    },
    {
        id: "project-manager",
        title: "Project Manager",
        industry: "Business",
        description: "Plan, execute, and close projects according to deadlines and budget",
        salaryRange: "SLE 4,000 - 10,000 (approx. $180 - $445)/month",
        salaryUSD: "SLE 4,000 - 10,000 (approx. $180 - $445)/month",
        demand: "High",
        requiredEducation: ["Management degree", "Project Management Professional (PMP) certification", "Business degree"],
        requiredSkills: ["Leadership", "Budget management", "Agile/Waterfall", "Scheduling", "Stakeholder communication"],
        localInstitutions: ["IPAM", "UNIMAK", "Njala University"],
        growthPotential: "Excellent - Crucial in NGOs, construction, and corporate sectors",
        keywords: ["project", "manager", "planning", "delivery", "management", "pm", "pmp"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "business-analyst",
        title: "Business Analyst",
        industry: "Business",
        description: "Analyze business processes and systems to find improvements and strategic solutions",
        salaryRange: "SLE 4,000 - 9,500 (approx. $180 - $420)/month",
        salaryUSD: "SLE 4,000 - 9,500 (approx. $180 - $420)/month",
        demand: "Medium",
        requiredEducation: ["Business administration degree", "Economics degree", "Data analysis courses"],
        requiredSkills: ["Data analysis", "Business modeling", "Requirements gathering", "Strategy", "Excel"],
        localInstitutions: ["IPAM", "Fourah Bay College", "Njala University"],
        growthPotential: "Strong - Businesses becoming more data-driven",
        keywords: ["business", "analyst", "strategy", "process", "analytics", "consulting"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "auditor",
        title: "Auditor",
        industry: "Finance",
        description: "Review financial records and systems to ensure accuracy and compliance with laws",
        salaryRange: "SLE 4,000 - 11,000 (approx. $180 - $490)/month",
        salaryUSD: "SLE 4,000 - 11,000 (approx. $180 - $490)/month",
        demand: "High",
        requiredEducation: ["Accounting degree", "ACCA/CPA/CIA certification"],
        requiredSkills: ["Financial auditing", "Attention to detail", "Legal knowledge", "Ethics", "Investigation"],
        localInstitutions: ["IPAM", "Fourah Bay College", "UNIMAK"],
        growthPotential: "Excellent - High demand for transparency and governance",
        keywords: ["audit", "compliance", "finance", "accounting", "risk", "internal", "investigation"],
        image: "/images/sections/careers/auditor.png"
    },
    {
        id: "mechanical-engineer",
        title: "Mechanical Engineer",
        industry: "Engineering",
        description: "Design, develop, and maintain mechanical systems and machinery",
        salaryRange: "SLE 4,500 - 10,500 (approx. $200 - $465)/month",
        salaryUSD: "SLE 4,500 - 10,500 (approx. $200 - $465)/month",
        demand: "Medium",
        requiredEducation: ["Mechanical engineering degree"],
        requiredSkills: ["Machinery maintenance", "CAD", "Thermodynamics", "Manufacturing", "Troubleshooting"],
        localInstitutions: ["Fourah Bay College", "Njala University"],
        growthPotential: "Good - Manufacturing and mining sectors growing",
        keywords: ["mechanical", "engineer", "machinery", "manufacturing", "maintenance", "workshop"],
        image: "/images/sections/careers/civil-engineer.png"
    },
    {
        id: "electrical-engineer",
        title: "Electrical Engineer",
        industry: "Engineering",
        description: "Design and maintain electrical equipment, systems, and power distribution",
        salaryRange: "SLE 4,000 - 10,000 (approx. $180 - $445)/month",
        salaryUSD: "SLE 4,000 - 10,000 (approx. $180 - $445)/month",
        demand: "High",
        requiredEducation: ["Electrical engineering degree", "Technical diploma"],
        requiredSkills: ["Power systems", "Electrical design", "Safety standards", "PCB design", "Wiring"],
        localInstitutions: ["Fourah Bay College", "Njala University", "Milton Margai University"],
        growthPotential: "Excellent - Critical for national power sector expansion",
        keywords: ["electrical", "engineer", "power", "grid", "electronics", "distribution", "electricity"],
        image: "/images/sections/careers/civil-engineer.png"
    },
    {
        id: "lab-technician",
        title: "Lab Technician",
        industry: "Healthcare",
        description: "Perform laboratory tests and analysis to assist in medical diagnosis and research",
        salaryRange: "SLE 2,500 - 6,000 (approx. $110 - $265)/month",
        salaryUSD: "SLE 2,500 - 6,000 (approx. $110 - $265)/month",
        demand: "High",
        requiredEducation: ["Medical laboratory technology diploma/degree"],
        requiredSkills: ["Testing procedures", "Equipment calibration", "Data recording", "Safety protocols", "Microbiology"],
        localInstitutions: ["COMAHS", "Njala University", "Hospital training programs"],
        growthPotential: "Strong - Laboratories expanding in hospitals nation-wide",
        keywords: ["lab", "laboratory", "technician", "medical", "testing", "blood", "analysis"],
        image: "/images/sections/careers/nurse-healthcare-worker.png"
    },
    {
        id: "pharmacy-technician",
        title: "Pharmacy Technician",
        industry: "Healthcare",
        description: "Assist pharmacists in preparing and dispensing medications and managing inventory",
        salaryRange: "SLE 2,200 - 5,500 (approx. $100 - $245)/month",
        salaryUSD: "SLE 2,200 - 5,500 (approx. $100 - $245)/month",
        demand: "High",
        requiredEducation: ["Pharmacy technician diploma"],
        requiredSkills: ["Medication knowledge", "Inventory management", "Customer service", "Safety", "Prescription processing"],
        localInstitutions: ["COMAHS", "Eastern Technical University", "Makeni Government Hospital School"],
        growthPotential: "Good - Retail pharmacy sector is growing rapidly",
        keywords: ["pharmacy", "tech", "medicines", "drugs", "dispensing", "pharmacist", "health"],
        image: "/images/sections/careers/nurse-healthcare-worker.png"
    },
    {
        id: "public-health-officer",
        title: "Public Health Officer",
        industry: "Healthcare",
        description: "Promote health and prevent disease within communities through programs and research",
        salaryRange: "SLE 3,500 - 8,500 (approx. $155 - $380)/month",
        salaryUSD: "SLE 3,500 - 8,500 (approx. $155 - $380)/month",
        demand: "High",
        requiredEducation: ["Public health degree", "Community health certificate"],
        requiredSkills: ["Data collection", "Community engagement", "Epidemiology", "Program planning", "Education"],
        localInstitutions: ["Njala University", "COMAHS", "University of Makeni"],
        growthPotential: "Very High - Strengthening health systems after Ebola/COVID",
        keywords: ["public", "health", "community", "prevention", "officer", "outreach", "epidemiology"],
        image: "/images/sections/careers/nurse-healthcare-worker.png"
    },
    {
        id: "environmental-scientist",
        title: "Environmental Scientist",
        industry: "Science",
        description: "Study and develop solutions to environmental problems like pollution and climate change",
        salaryRange: "SLE 3,500 - 8,000 (approx. $155 - $355)/month",
        salaryUSD: "SLE 3,500 - 8,000 (approx. $155 - $355)/month",
        demand: "Medium",
        requiredEducation: ["Environmental science degree", "Geology/Science degree"],
        requiredSkills: ["Environmental assessment", "Data analysis", "Ecology", "Conservation", "Policy knowledge"],
        localInstitutions: ["Njala University", "Fourah Bay College", "EBKUST"],
        growthPotential: "Growing - Increasing focus on climate and conservation",
        keywords: ["environment", "climate", "conservation", "nature", "science", "ecology", "green"],
        image: "/images/sections/careers/civil-engineer.png"
    },
    {
        id: "agripreneur",
        title: "Agripreneur",
        industry: "Agriculture",
        description: "Combine entrepreneurship with agriculture to run innovative and commercial farm businesses",
        salaryRange: "Varies (SLE 2,500 - 15,000+ per month)",
        salaryUSD: "Varies (SLE 2,500 - 15,000+ per month)",
        demand: "High",
        requiredEducation: ["Business training", "Agricultural degree/certificate", "Practical farming experience"],
        requiredSkills: ["Business planning", "Farm management", "Marketing", "Innovation", "Financial literacy"],
        localInstitutions: ["Njala University", "Sierra Leone Chamber of Commerce", "Agro-hubs"],
        growthPotential: "Excellent - High priority for food security in SL",
        keywords: ["agripreneur", "farming", "business", "innovation", "commercial", "agric", "startup"],
        image: "/images/sections/careers/agripreneur.png"
    },
    {
        id: "logistics-manager",
        title: "Logistics Manager",
        industry: "Supply Chain",
        description: "Plan and coordinate the movement and storage of goods and services",
        salaryRange: "SLE 3,500 - 9,000 (approx. $155 - $400)/month",
        salaryUSD: "SLE 3,500 - 9,000 (approx. $155 - $400)/month",
        demand: "High",
        requiredEducation: ["Supply chain management degree", "Business administration", "Logistics diploma"],
        requiredSkills: ["Strategic planning", "Inventory control", "Transportation", "Warehousing", "Detail-oriented"],
        localInstitutions: ["IPAM", "UNIMAK", "BlueCrest"],
        growthPotential: "Strong - Increasing international trade and NGO activity",
        keywords: ["logistics", "supply", "chain", "transport", "warehouse", "delivery", "shipping"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "hr-officer",
        title: "HR Officer",
        industry: "Business",
        description: "Manage recruitment, employee relations, and administrative tasks for an organization",
        salaryRange: "SLE 3,000 - 7,500 (approx. $135 - $330)/month",
        salaryUSD: "SLE 3,000 - 7,500 (approx. $135 - $330)/month",
        demand: "Medium",
        requiredEducation: ["Human Resources degree", "Management degree", "Business administration"],
        requiredSkills: ["Recruitment", "Communication", "Labor laws", "Conflict resolution", "Administration"],
        localInstitutions: ["IPAM", "UNIMAK", "Njala University"],
        growthPotential: "Stable - Every organization needs people management",
        keywords: ["hr", "personnel", "hiring", "employees", "human", "resources", "office"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "legal-assistant",
        title: "Legal Assistant",
        industry: "Legal",
        description: "Support lawyers by conducting research, drafting documents, and managing legal cases",
        salaryRange: "SLE 2,500 - 6,000 (approx. $110 - $265)/month",
        salaryUSD: "SLE 2,500 - 6,000 (approx. $110 - $265)/month",
        demand: "Medium",
        requiredEducation: ["Law degree (LLB) or diploma", "Legal studies certificate"],
        requiredSkills: ["Research", "Writing", "Attention to detail", "Legal terminology", "Confidentiality"],
        localInstitutions: ["Fourah Bay College", "Unimak", "Technical colleges"],
        growthPotential: "Good - Growing legal needs for businesses and individuals",
        keywords: ["legal", "assistant", "lawyer", "office", "clerk", "courts", "research"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "content-creator",
        title: "Content Creator",
        industry: "Media",
        description: "Produce engaging content for digital platforms like social media, blogs, and video",
        salaryRange: "Varies (SLE 2,000 - 10,000+ per month)",
        salaryUSD: "Varies (SLE 2,000 - 10,000+ per month)",
        demand: "High",
        requiredEducation: ["Mass communication", "Digital marketing courses", "Creative portfolio"],
        requiredSkills: ["Video editing", "Storytelling", "Social media", "Photography", "Branding"],
        localInstitutions: ["Fourah Bay College", "Limkokwing University", "Media studios"],
        growthPotential: "Excellent - Exploding interest in digital media and influencers in SL",
        keywords: ["content", "creator", "digital", "social", "media", "video", "influencer"],
        image: "/images/sections/careers/account-manager.png",
        universityIds: ["limkokwing", "fbc"]
    },
    {
        id: "translator",
        title: "Translator",
        industry: "Communication",
        description: "Convert written text or spoken words from one language to another, including local languages",
        salaryRange: "SLE 2,500 - 7,000 (approx. $110 - $310)/month",
        salaryUSD: "SLE 2,500 - 7,000 (approx. $110 - $310)/month",
        demand: "Medium",
        requiredEducation: ["Linguistics degree", "Fluency in multiple languages", "Education degree"],
        requiredSkills: ["Bilingualism", "Writing", "Cultural sensitivity", "Interpretation", "Accuracy"],
        localInstitutions: ["Fourah Bay College", "Njala University", "Language centers"],
        growthPotential: "Stable - Essential for NGOs, international business, and government",
        keywords: ["translator", "language", "krio", "english", "french", "linguistics", "communication"],
        image: "/images/sections/careers/teacher-educator.png"
    },
    {
        id: "tourism-guide",
        title: "Tourism Guide",
        industry: "Tourism",
        description: "Accompany tourists and provide information about Sierra Leone's attractions and culture",
        salaryRange: "Varies (SLE 2,000 - 6,000+ per month)",
        salaryUSD: "Varies (SLE 2,000 - 6,000+ per month)",
        demand: "Medium",
        requiredEducation: ["Tourism and hospitality degree/diploma", "Heritage studies"],
        requiredSkills: ["Communication", "History knowledge", "First aid", "Hospitality", "Customer service"],
        localInstitutions: ["Milton Margai University", "Tourism training centers"],
        growthPotential: "High - Sierra Leone rebranding as a tourism hub",
        keywords: ["tourism", "guide", "travel", "visitor", "nature", "heritage", "beaches"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "chef-culinary-artist",
        title: "Chef/Culinary Artist",
        industry: "Hospitality",
        description: "Prepare and oversee food preparation in restaurants, hotels, or private settings",
        salaryRange: "SLE 2,500 - 8,000 (approx. $110 - $355)/month",
        salaryUSD: "SLE 2,500 - 8,000 (approx. $110 - $355)/month",
        demand: "High",
        requiredEducation: ["Culinary arts diploma", "Apprenticeship", "Hospitality degree"],
        requiredSkills: ["Cooking", "Food safety", "Creativity", "Teamwork", "Menu planning"],
        localInstitutions: ["Milton Margai University", "Hospitality schools", "Hotels"],
        growthPotential: "Excellent - Expanding restaurant and hotel scene in Freetown",
        keywords: ["chef", "cook", "restaurant", "food", "hospitality", "hotel", "kitchen"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "welder-metal-fabricator",
        title: "Welder/Metal Fabricator",
        industry: "Skilled Trade",
        description: "Join metal parts and fabricate structures using various welding techniques",
        salaryRange: "SLE 2,500 - 7,500 (approx. $110 - $330)/month",
        salaryUSD: "SLE 2,500 - 7,500 (approx. $110 - $330)/month",
        demand: "High",
        requiredEducation: ["Technical vocational training", "Apprenticeship"],
        requiredSkills: ["Welding techniques", "Blueprint reading", "Safety", "Measurement", "Metalwork"],
        localInstitutions: ["Milton Margai University", "Eastern Technical University", "Technical institutes"],
        growthPotential: "Strong - Construction and repairs always in demand",
        keywords: ["welder", "metal", "fabrication", "construction", "iron", "workshop", "trade"],
        image: "/images/sections/careers/auto-mechanic.png"
    },
    {
        id: "plumber",
        title: "Plumber",
        industry: "Skilled Trade",
        description: "Install and repair pipes and systems for water distribution and disposal",
        salaryRange: "SLE 2,000 - 6,000 (approx. $90 - $265)/month",
        salaryUSD: "SLE 2,000 - 6,000 (approx. $90 - $265)/month",
        demand: "High",
        requiredEducation: ["Technical vocational training", "Apprenticeship"],
        requiredSkills: ["Pipe fitting", "Troubleshooting", "Blueprint reading", "Safety", "Water systems"],
        localInstitutions: ["Technical institutes", "Trade schools", "Freetown Technical Institute"],
        growthPotential: "Stable - Every building needs plumbing",
        keywords: ["plumber", "pipe", "water", "sewage", "construction", "repair", "trade"],
        image: "/images/sections/careers/auto-mechanic.png"
    },
    {
        id: "carpenter",
        title: "Carpenter",
        industry: "Skilled Trade",
        description: "Construct and repair structures and items from wood and other materials",
        salaryRange: "SLE 2,000 - 6,000 (approx. $90 - $265)/month",
        salaryUSD: "SLE 2,000 - 6,000 (approx. $90 - $265)/month",
        demand: "High",
        requiredEducation: ["Technical vocational training", "Apprenticeship"],
        requiredSkills: ["Woodworking", "Furniture making", "Framing", "Tool usage", "Creativity"],
        localInstitutions: ["Technical institutes", "Milton Margai University", "Carpenter workshops"],
        growthPotential: "Good - Building and furniture industries always active",
        keywords: ["carpenter", "wood", "furniture", "building", "construction", "trade", "joiner"],
        image: "/images/sections/careers/auto-mechanic.png"
    },
    {
        id: "financial-analyst",
        title: "Financial Analyst",
        industry: "Finance",
        description: "Evaluate financial data to help businesses and individuals make investment decisions",
        salaryRange: "SLE 4,500 - 12,000 (approx. $200 - $530)/month",
        salaryUSD: "SLE 4,500 - 12,000 (approx. $200 - $530)/month",
        demand: "Medium",
        requiredEducation: ["Finance degree", "Economics degree", "ACCA/CFA certification"],
        requiredSkills: ["Financial modeling", "Excel", "Data analysis", "Strategy", "Reporting"],
        localInstitutions: ["IPAM", "Fourah Bay College", "Banking institutes"],
        growthPotential: "Strong - Banking and finance sector maturing",
        keywords: ["financial", "analyst", "investment", "finance", "data", "banking", "economy"],
        image: "/images/sections/careers/auditor.png"
    },
    {
        id: "insurance-officer",
        title: "Insurance Officer",
        industry: "Finance",
        description: "Process insurance applications, claims, and sales for risk protection services",
        salaryRange: "SLE 3,000 - 8,000 (approx. $135 - $355)/month",
        salaryUSD: "SLE 3,000 - 8,000 (approx. $135 - $355)/month",
        demand: "Medium",
        requiredEducation: ["Business degree", "Insurance studies certificate", "Economics"],
        requiredSkills: ["Sales", "Risk assessment", "Communication", "Customer service", "Underwriting"],
        localInstitutions: ["IPAM", "UNIMAK", "BlueCrest"],
        growthPotential: "Increasing - People becoming more aware of insurance",
        keywords: ["insurance", "risk", "protection", "claims", "sales", "finance", "policy"],
        image: "/images/sections/careers/auditor.png"
    },
    {
        id: "risk-safety-officer",
        title: "Risk & Safety Officer",
        industry: "Business",
        description: "Identify and minimize organizational risks and ensure health and safety standards are met",
        salaryRange: "SLE 4,000 - 9,500 (approx. $180 - $420)/month",
        salaryUSD: "SLE 4,000 - 9,500 (approx. $180 - $420)/month",
        demand: "High",
        requiredEducation: ["Environmental health degree", "Safety management (NEBOSH)", "Management degree"],
        requiredSkills: ["Risk assessment", "OSHA knowledge", "Training", "Accident investigation", "Reporting"],
        localInstitutions: ["Njala University", "Engineering firms", "Consultancy firms"],
        growthPotential: "Strong - Mandatory in mining, construction, and formal offices",
        keywords: ["risk", "safety", "health", "compliance", "officer", "hse", "protection"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "data-analyst",
        title: "Data Analyst",
        industry: "Technology",
        description: "Interpret data and turn it into information which can offer ways to improve a business",
        salaryRange: "SLE 4,000 - 9,500 (approx. $180 - $420)/month",
        salaryUSD: "SLE 4,000 - 9,500 (approx. $180 - $420)/month",
        demand: "High",
        requiredEducation: ["Data science degree", "IT degree", "Statistics certificate"],
        requiredSkills: ["SQL", "Excel", "Data visualization", "Statistics", "Problem-solving"],
        localInstitutions: ["IPAM", "Fourah Bay College", "BlueCrest College"],
        growthPotential: "Excellent - High demand in NGOs and banking",
        keywords: ["data", "analyst", "analytics", "statistics", "excel", "sql", "insights"],
        image: "/images/sections/careers/software-developer.png"
    },
    {
        id: "ict-support-specialist",
        title: "ICT Support Specialist",
        industry: "Technology",
        description: "Provide technical assistance and support related to computer systems, hardware, or software",
        salaryRange: "SLE 2,500 - 6,500 (approx. $110 - $290)/month",
        salaryUSD: "SLE 2,500 - 6,500 (approx. $110 - $290)/month",
        demand: "High",
        requiredEducation: ["Technical diploma in IT", "A+ Certification", "IT degree"],
        requiredSkills: ["Troubleshooting", "Hardware repair", "Customer service", "Software installation", "Networking"],
        localInstitutions: ["Eastern Technical University", "Milton Margai University", "Technical institutes"],
        growthPotential: "Strong - Every organization requires IT maintenance",
        keywords: ["ict", "support", "it", "hardware", "software", "tech", "helpdesk"],
        image: "/images/sections/careers/software-developer.png"
    },
    {
        id: "digital-marketer",
        title: "Digital Marketer",
        industry: "Business",
        description: "Produce engaging content for digital platforms to promote brands and products",
        salaryRange: "SLE 3,000 - 8,000 (approx. $135 - $355)/month",
        salaryUSD: "SLE 3,000 - 8,000 (approx. $135 - $355)/month",
        demand: "High",
        requiredEducation: ["Marketing degree", "Digital marketing certifications", "Mass communication"],
        requiredSkills: ["SEO", "Social media ads", "Content strategy", "Analytics", "Copywriting"],
        localInstitutions: ["IPAM", "BlueCrest", "Limkokwing University"],
        growthPotential: "Excellent - Rapidly expanding digital economy",
        keywords: ["digital", "marketing", "social", "media", "seo", "ads", "online"],
        image: "/images/sections/careers/account-manager.png",
        universityIds: ["ipam", "bluecrest", "limkokwing"]
    },
    {
        id: "agricultural-engineer",
        title: "Agricultural Engineer",
        industry: "Engineering",
        description: "Apply engineering principles to agricultural production and processing",
        salaryRange: "SLE 4,500 - 10,000 (approx. $200 - $445)/month",
        salaryUSD: "SLE 4,500 - 10,000 (approx. $200 - $445)/month",
        demand: "High",
        requiredEducation: ["Agricultural engineering degree"],
        requiredSkills: ["Farm machinery design", "Irrigation systems", "Post-harvest technology", "CAD", "Environmental science"],
        localInstitutions: ["Njala University", "Fourah Bay College"],
        growthPotential: "Excellent - Key to modernizing Sierra Leone's farming",
        keywords: ["agricultural", "engineer", "farming", "machinery", "irrigation", "agric"],
        image: "/images/sections/careers/agricultural-engineer.png"
    },
    {
        id: "entrepreneur",
        title: "Entrepreneur",
        industry: "Business",
        description: "Start and manage your own business, taking on financial risks for profit",
        salaryRange: "Varies (SLE 2,000 - 25,000+ per month)",
        salaryUSD: "Varies (SLE 2,000 - 25,000+ per month)",
        demand: "High",
        requiredEducation: ["Business training", "Practical experience", "Entrepreneurship diploma"],
        requiredSkills: ["Business planning", "Financial management", "Marketing", "Risk taking", "Networking"],
        localInstitutions: ["IPAM", "Sierra Leone Chamber of Commerce", "Business incubators"],
        growthPotential: "Infinite - Core driver of the local economy",
        keywords: ["entrepreneur", "business", "startup", "owner", "venture", "innovation"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "sales-officer",
        title: "Sales Officer",
        industry: "Business",
        description: "Identify and meet customer needs by promoting and selling products or services",
        salaryRange: "SLE 2,000 - 7,000 (approx. $90 - $310)/month",
        salaryUSD: "SLE 2,000 - 7,000 (approx. $90 - $310)/month",
        demand: "High",
        requiredEducation: ["Business administration degree", "Sales training", "Linguistics"],
        requiredSkills: ["Persuasion", "Communication", "Customer relationship", "Negotiation", "Reporting"],
        localInstitutions: ["IPAM", "UNIMAK", "BlueCrest"],
        growthPotential: "Strong - Crucial for telecommunications and retail",
        keywords: ["sales", "selling", "marketing", "customer", "leads", "revenue"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "hospitality-manager",
        title: "Hospitality Manager",
        industry: "Hospitality",
        description: "Oversee the daily operations of hotels, restaurants, and other travel-related businesses",
        salaryRange: "SLE 4,000 - 12,000 (approx. $180 - $530)/month",
        salaryUSD: "SLE 4,000 - 12,000 (approx. $180 - $530)/month",
        demand: "Medium",
        requiredEducation: ["Hospitality management degree", "Tourism studies"],
        requiredSkills: ["Management", "Customer service", "Budgeting", "Events planning", "Staff supervision"],
        localInstitutions: ["Milton Margai University", "Eastern Technical University"],
        growthPotential: "Good - Growing tourism and international visitor numbers",
        keywords: ["hospitality", "hotel", "manager", "tourism", "resort", "service"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "construction-supervisor",
        title: "Construction Supervisor",
        industry: "Engineering",
        description: "Oversee and manage workers and activities on construction sites",
        salaryRange: "SLE 3,500 - 9,000 (approx. $155 - $400)/month",
        salaryUSD: "SLE 3,500 - 9,000 (approx. $155 - $400)/month",
        demand: "High",
        requiredEducation: ["Construction management degree", "Civil engineering diploma", "Technical training"],
        requiredSkills: ["Site management", "Safety oversight", "Blueprint reading", "Leadership", "Project coordination"],
        localInstitutions: ["Fourah Bay College", "Milton Margai University", "Technical institutes"],
        growthPotential: "Strong - Consistent infrastructure and residential growth",
        keywords: ["construction", "supervisor", "site", "building", "foreman", "civil"],
        image: "/images/sections/careers/civil-engineer.png"
    },
    {
        id: "auto-mechanic",
        title: "Auto Mechanic",
        industry: "Skilled Trade",
        description: "Inspect, maintain, and repair vehicles including cars and trucks",
        salaryRange: "SLE 2,500 - 8,000 (approx. $110 - $355)/month",
        salaryUSD: "SLE 2,500 - 8,000 (approx. $110 - $355)/month",
        demand: "High",
        requiredEducation: ["Technical vocational training", "Apprenticeship", "Automotive certificate"],
        requiredSkills: ["Engine repair", "Diagnostics", "Brake systems", "Electrical systems", "Problem-solving"],
        localInstitutions: ["Milton Margai University", "Ernest Bai Koroma University", "Technical institutes"],
        growthPotential: "Excellent - High volume of vehicles needing maintenance",
        keywords: ["auto", "mechanic", "vehicle", "car", "engine", "repair", "transport"],
        image: "/images/sections/careers/auto-mechanic.png"
    },
    {
        id: "machine-operator",
        title: "Machine Operator",
        industry: "Skilled Trade",
        description: "Set up and operate variety of machines used in manufacturing or construction",
        salaryRange: "SLE 2,500 - 7,000 (approx. $110 - $310)/month",
        salaryUSD: "SLE 2,500 - 7,000 (approx. $110 - $310)/month",
        demand: "High",
        requiredEducation: ["Technical training", "Safety certifications", "On-the-job training"],
        requiredSkills: ["Machine operation", "Safety adherence", "Physical stamina", "Maintenance", "Precision"],
        localInstitutions: ["Technical institutes", "Mining training centers"],
        growthPotential: "Strong - Growing industrial and mining sites",
        keywords: ["machine", "operator", "factory", "mining", "manufacturing", "production"],
        image: "/images/sections/careers/auto-mechanic.png"
    },
    {
        id: "quality-control-inspector",
        title: "Quality Control Inspector",
        industry: "Business",
        description: "Examine products and materials for defects or deviations from specifications",
        salaryRange: "SLE 3,000 - 8,500 (approx. $135 - $380)/month",
        salaryUSD: "SLE 3,000 - 8,500 (approx. $135 - $380)/month",
        demand: "Medium",
        requiredEducation: ["Management degree", "Science degree", "Quality management certificate"],
        requiredSkills: ["Attention to detail", "Testing procedures", "Regulatory compliance", "Reporting", "Standards knowledge"],
        localInstitutions: ["Njala University", "Bureau of Standards training"],
        growthPotential: "Stable - Important for export and manufacturing standards",
        keywords: ["quality", "control", "inspector", "standards", "compliance", "defects"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "account-manager",
        title: "Account Manager",
        industry: "Business",
        description: "Manage relationships with specific clients and ensure their needs are met",
        salaryRange: "SLE 4,000 - 10,000 (approx. $180 - $445)/month",
        salaryUSD: "SLE 4,000 - 10,000 (approx. $180 - $445)/month",
        demand: "Medium",
        requiredEducation: ["Business degree", "Marketing degree", "Public relations"],
        requiredSkills: ["Client relations", "Negotiation", "Sales", "Communication", "Strategic planning"],
        localInstitutions: ["IPAM", "UNIMAK", "BlueCrest"],
        growthPotential: "Good - Essential for b2b companies and banks",
        keywords: ["account", "manager", "clients", "relationships", "business", "sales"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "supply-chain-coordinator",
        title: "Supply Chain Coordinator",
        industry: "Supply Chain",
        description: "Oversee the lifecycle of products, from procurement to distribution",
        salaryRange: "SLE 3,500 - 9,500 (approx. $155 - $420)/month",
        salaryUSD: "SLE 3,500 - 9,500 (approx. $155 - $420)/month",
        demand: "High",
        requiredEducation: ["Supply chain management degree", "Logistics diploma"],
        requiredSkills: ["Procurement", "Inventory tracking", "Vendor management", "Analytics", "Organization"],
        localInstitutions: ["IPAM", "UNIMAK", "Njala University"],
        growthPotential: "Strong - Critical for NGOs and international organizations",
        keywords: ["supply", "chain", "procurement", "coordinator", "logistics", "shipping"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "trainer-educator",
        title: "Trainer/Educator",
        industry: "Education",
        description: "Develop and deliver training programs to enhance skills and knowledge",
        salaryRange: "SLE 3,000 - 8,000 (approx. $135 - $355)/month",
        salaryUSD: "SLE 3,000 - 8,000 (approx. $135 - $355)/month",
        demand: "Medium",
        requiredEducation: ["Education degree", "Subject matter expertise", "Facilitation certificate"],
        requiredSkills: ["Presentation", "Curriculum design", "Mentorship", "Public speaking", "Assessment"],
        localInstitutions: ["Fourah Bay College", "IPAM", "NGO training workshops"],
        growthPotential: "Good - Focus on vocational and corporate training",
        keywords: ["trainer", "educator", "coach", "skills", "workshop", "teaching"],
        image: "/images/sections/careers/adult-education.jpg"
    },
    {
        id: "mining-geologist",
        title: "Mining Geologist",
        industry: "Mining",
        description: "Study the Earth's structure to locate and manage mineral resources like iron ore, diamonds, and bauxite.",
        salaryRange: "SLE 5,000 - 15,000 (approx. $220 - $660)/month",
        salaryUSD: "SLE 5,000 - 15,000 (approx. $220 - $660)/month",
        demand: "High",
        requiredEducation: ["BSc Geology", "Earth Science degree"],
        requiredSkills: ["Mineral identification", "Mapping", "GIS", "Safety compliance", "Reporting"],
        localInstitutions: ["Fourah Bay College", "National Minerals Agency training"],
        growthPotential: "Excellent - Core part of the extractive industry",
        keywords: ["geology", "rocks", "mining", "extraction", "minerals", "science"],
        image: "/images/sections/careers/mining-engineer.png"
    },
    {
        id: "fisheries-officer",
        title: "Fisheries Officer",
        industry: "Agriculture",
        description: "Manage and conserve fish stocks, oversee fishing activities, and support the blue economy.",
        salaryRange: "SLE 3,000 - 8,000 (approx. $135 - $355)/month",
        salaryUSD: "SLE 3,000 - 8,000 (approx. $135 - $355)/month",
        demand: "High",
        requiredEducation: ["BSc Fisheries", "Marine biology", "Environment science"],
        requiredSkills: ["Marine ecology", "Data collection", "Policy enforcement", "Community outreach"],
        localInstitutions: ["Njala University", "University of Sierra Leone (IMBO)"],
        growthPotential: "Strong - High focus on protecting oceanic resources",
        keywords: ["fish", "fisheries", "ocean", "marine", "blue economy", "conservation"],
        image: "/images/sections/careers/agripreneur.png"
    },
    {
        id: "public-administrator",
        title: "Public Administrator",
        industry: "Government",
        description: "Manage government agencies, implement public policies, and oversee community programs to improve public welfare.",
        salaryRange: "SLE 2,800 - 8,500 (approx. $125 - $380)/month",
        salaryUSD: "SLE 2,800 - 8,500 (approx. $125 - $380)/month",
        demand: "Medium",
        requiredEducation: ["Public Administration degree", "Management degree", "Social sciences"],
        requiredSkills: ["Policy analysis", "Public relations", "Budgeting", "Governance", "Strategic planning"],
        localInstitutions: ["IPAM", "Fourah Bay College", "Njala University"],
        growthPotential: "Stable - Essential for efficient government and NGO sectors",
        keywords: ["government", "public", "admin", "policy", "governance", "civil service"],
        image: "/images/sections/careers/account-manager.png"
    },
    {
        id: "mass-communication-specialist",
        title: "Mass Communication Specialist",
        industry: "Media",
        description: "Craft and deliver information to the public via various channels like television, radio, and social media.",
        salaryRange: "SLE 2,500 - 7,500 (approx. $110 - $330)/month",
        salaryUSD: "SLE 2,500 - 7,500 (approx. $110 - $330)/month",
        demand: "High",
        requiredEducation: ["Mass Communication degree", "Journalism degree", "Media studies"],
        requiredSkills: ["Public speaking", "Media production", "Storytelling", "Writing", "Public relations"],
        localInstitutions: ["Fourah Bay College", "University of Makeni", "Milton Margai University"],
        growthPotential: "Strong - Media and communication landscape evolving rapidly in SL",
        keywords: ["media", "comm", "mass", "broadcasting", "radio", "tv", "communication"],
        image: "/images/sections/careers/account-manager.png"
    }
];

export const CAREER_CATEGORIES = {
    technology: ["Software Developer", "Network Administrator", "Cybersecurity Analyst", "UX/UI Designer", "Telecommunications Technician", "Data Analyst", "ICT Support Specialist"],
    healthcare: ["Nurse/Healthcare Worker", "Lab Technician", "Pharmacy Technician", "Public Health Officer"],
    agriculture: ["Agricultural Officer", "Agripreneur", "Fisheries Officer"],
    education: ["Teacher/Educator", "Trainer/Educator"],
    mining: ["Mining Engineer", "Mining Geologist"],
    finance: ["Accountant", "Auditor", "Financial Analyst", "Insurance Officer"],
    engineering: ["Civil Engineer", "Mechanical Engineer", "Electrical Engineer", "Agricultural Engineer", "Construction Supervisor"],
    business: ["Marketing Manager", "Project Manager", "Business Analyst", "HR Officer", "Risk & Safety Officer", "Entrepreneur", "Sales Officer", "Quality Control Inspector", "Account Manager"],
    nonprofit: ["NGO Program Officer"],
    trades: ["Electrician", "Welder/Metal Fabricator", "Plumber", "Carpenter", "Auto Mechanic", "Machine Operator"],
    media: ["Journalist", "Graphic Designer", "Content Creator", "Mass Communication Specialist"],
    science: ["Environmental Scientist"],
    supplychain: ["Logistics Manager", "Supply Chain Coordinator"],
    legal: ["Legal Assistant"],
    communication: ["Translator"],
    tourism: ["Tourism Guide"],
    hospitality: ["Chef/Culinary Artist", "Hospitality Manager"],
    government: ["Public Administrator"]
};

export const INSTITUTIONS = [
    {
        id: "fbc",
        name: "Fourah Bay College (FBC)",
        specializations: ["Law", "Engineering (Civil, Mechanical, Electrical)", "Pure & Applied Sciences", "Arts", "Social Sciences"],
        location: "Mount Aureol, Freetown",
        image: "/images/sections/universities/fbc.jpg"
    },
    {
        id: "ipam",
        name: "IPAM (University of Sierra Leone)",
        specializations: ["Accounting", "Business Administration", "Public Administration", "Information Systems", "Financial Services"],
        location: "Tower Hill, Freetown",
        image: "/images/sections/universities/ipam.jpg"
    },
    {
        id: "comahs",
        name: "COMAHS (University of Sierra Leone)",
        specializations: ["Medicine", "Nursing", "Pharmacy", "Medical Laboratory Science", "Public Health"],
        location: "Kossoh Town / Connaught",
        image: "/images/sections/universities/comahs.jpg"
    },
    {
        id: "njala",
        name: "Njala University",
        specializations: ["Agriculture", "Environmental Sciences", "Natural Resources Management", "Food Science", "Education", "Engineering"],
        location: "Njala / Bo",
        image: "/images/sections/universities/njala.jpg"
    },
    {
        id: "unimak",
        name: "University of Makeni (UNIMAK)",
        specializations: ["Information Technology", "Mass Communication", "Public Health", "Accounting", "Education", "Law"],
        location: "Makeni",
        image: "/images/sections/universities/unimak.jpg"
    },
    {
        id: "mmtu",
        name: "Milton Margai University of Education and Technology",
        specializations: ["Tourism & Hospitality", "Performing Arts", "Technical Education", "Engineering", "Social Sciences"],
        location: "Goderich / Congo Cross",
        image: "/images/sections/universities/mmtu.jpg"
    },
    {
        id: "etu",
        name: "Eastern Technical University",
        specializations: ["Agriculture", "Technical Studies", "Engineering", "Education", "Medical Sciences"],
        location: "Kenema",
        image: "/images/sections/universities/etu.jpg"
    },
    {
        id: "ebkust",
        name: "Ernest Bai Koroma University",
        specializations: ["Education", "Agriculture", "Social Sciences", "Pure & Applied Sciences"],
        location: "Makeni / Magburaka",
        image: "/images/sections/universities/ebkust.jpg"
    },
    {
        id: "bluecrest",
        name: "BlueCrest College",
        specializations: ["Information Technology", "Fashion Design", "Business Administration"],
        location: "Freetown",
        image: "/images/sections/universities/campus.png" // Fallback
    },
    {
        id: "limkokwing",
        name: "Limkokwing University",
        specializations: ["Creative Technology", "Design", "Communication", "Information Technology"],
        location: "Hill Station, Freetown",
        image: "/images/sections/universities/limkokwing.jpg"
    },
    {
        id: "orange-digital",
        name: "Orange Digital Center",
        specializations: ["Coding", "Digital Marketing", "Entrepreneurship", "UI/UX Design"],
        location: "Freetown",
        type: "Vocational/Technical",
        image: "/images/sections/universities/campus.png" // Fallback
    },
    {
        id: "gti",
        name: "Government Technical Institute (GTI)",
        specializations: ["Automobile Mechanics", "Carpentry", "Welding", "Electrical Installation", "Plumbing"],
        location: "Various Locations",
        type: "Vocational",
        image: "/images/sections/universities/campus.png" // Fallback
    }
];

export const ONLINE_RESOURCES = [
    "freeCodeCamp (coding)",
    "Coursera (various subjects)",
    "Khan Academy (math, science)",
    "edX (university courses)",
    "YouTube tutorials",
    "Codecademy (programming)",
    "Udemy (affordable courses)",
    "Google Digital Skills"
];

export const PREVIEW_ROADMAP: RoadmapTask[] = [
    {
        id: "1",
        title: "Set Clear Career Goals",
        description: "Identify your interests, strengths, and career aspirations. Research potential career paths and set SMART goals.",
        duration: "1 week",
        completed: false,
        week: 1,
    },
    {
        id: "2",
        title: "Build Foundational Academic Skills",
        description: "Strengthen core subjects like Mathematics, English, Science, and critical thinking skills essential for any career.",
        duration: "4 weeks",
        completed: false,
        week: 2,
    },
    {
        id: "3",
        title: "Develop Communication Skills",
        description: "Practice writing, public speaking, active listening, and professional communication in various contexts.",
        duration: "3 weeks",
        completed: false,
        week: 6,
    },
    {
        id: "4",
        title: "Learn Digital Literacy",
        description: "Master essential computer skills, Microsoft Office, email etiquette, and online research techniques.",
        duration: "2 weeks",
        completed: false,
        week: 9,
    }
];

